FROM python:3.9.12-slim-buster

WORKDIR /auth/

RUN apt update &&\
    apt install -y curl gcc cmake

ADD requirements.txt /auth
RUN pip3 install -r requirements.txt

ADD / /auth

ADD /.env.docker /auth/.env

ADD /app.py /

ADD /grpc_server.py /

EXPOSE 55005/tcp

ENTRYPOINT\
        cd / &&\
        python3 /grpc_server.py
