# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: user.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nuser.proto\x12\x04\x61uth\"\x14\n\x05Token\x12\x0b\n\x03jwt\x18\x01 \x01(\t\"\x16\n\x05Roles\x12\r\n\x05roles\x18\x01 \x03(\t2+\n\x04user\x12#\n\x05whois\x12\x0b.auth.Token\x1a\x0b.auth.Roles\"\x00\x62\x06proto3')



_TOKEN = DESCRIPTOR.message_types_by_name['Token']
_ROLES = DESCRIPTOR.message_types_by_name['Roles']
Token = _reflection.GeneratedProtocolMessageType('Token', (_message.Message,), {
  'DESCRIPTOR' : _TOKEN,
  '__module__' : 'user_pb2'
  # @@protoc_insertion_point(class_scope:auth.Token)
  })
_sym_db.RegisterMessage(Token)

Roles = _reflection.GeneratedProtocolMessageType('Roles', (_message.Message,), {
  'DESCRIPTOR' : _ROLES,
  '__module__' : 'user_pb2'
  # @@protoc_insertion_point(class_scope:auth.Roles)
  })
_sym_db.RegisterMessage(Roles)

_USER = DESCRIPTOR.services_by_name['user']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _TOKEN._serialized_start=20
  _TOKEN._serialized_end=40
  _ROLES._serialized_start=42
  _ROLES._serialized_end=64
  _USER._serialized_start=66
  _USER._serialized_end=109
# @@protoc_insertion_point(module_scope)
