@startuml

!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml
HIDE_STEREOTYPE()

AddBoundaryTag("new", $bgColor="lightgreen", $fontColor="green", $borderColor="green")
AddElementTag("new_container", $fontColor="#black", $bgColor="lightgreen")
AddElementTag("external", $fontColor="#black", $bgColor="grey")

Person(Client, "Client", "frontend")
Person(Admin, "Administrator")

System_Boundary(AdminPanel, "Admin Panel"){
Container(AdminDjango, "API", "Django")
ContainerDb(Postgres, "DB", "PostgerSQL")
}

System_Boundary(FullTextSearch, "Full Text Search"){
Container(SearchFastApiBackend, "API", "FastApi")
Container(Etl, "Etl", "Python")
ContainerDb(SearchElastic, "DB", "ElasticSearch")
ContainerDb(SearchRedis, "Cache", "Redis")
}

System_Boundary(Auth, "Auth"){
Container(AuthFlask, "API", "Flask")
ContainerDb(AuthRedis, "Сache", "Redis")
ContainerDb(AuthPostgres, "DB", "PostgreSQL")
}

Container(Ya, "Yandex", "external SSO", $tags="external")
Container(Vk, "VK", "external SSO", $tags="external")

System_Boundary(UGC, "UGC"){
Container(EventApi, "EventApi", "FastApi", "АПИ для плеера")
ContainerQueue(Kafka, "Queue", "Kafka")
Container(ReviewsApi, "ReviewsApi", "FastApi", "API для работы с лайками, закладками и отзывами")
ContainerDb(MongoDb, "DB", "MongoDB", "База данных для лайков, закладок и отзывов")
}

System_Boundary(OLAP, "OLAP"){
Container(KafkaEtlClickhouse, Etl, "Python")
ContainerDb(ClickHouse, "DB", "ClickHouse")
Container(SomeAnalitics, "BI", "", "Интерфейс к базе данных")
}

System_Boundary(ELK, "Log Collector - ELK"){
Container(ReviewsLogstash, "Logs collect", "Logstash", "Сборка логов из остальных сервисов")
ContainerDb(ReviewsElastic, "Logs store", "ElasticSearch", "База данных для сбора логов")
Container(ReviewsKibana, "Logs view", "Kibana", "Интерфейс для просмотра логов")
}

System_Boundary(notifications, "Notifications service"){
Container(NotificationsReciveApi, "Notification reciver", "API", "Получение уведомлений email/websocket")
ContainerQueue(RabbitMq, "Notification queue store", "RabbitMQ", "Хранение уведомлений")
Container(NotificationsSendApi, "Notification sender", "API", "Отправка уведомлений email/websocket")
}

System_Boundary(billing, "Billing service"){
Container(BillingAdminPriceSetterApi, "Subscribtion price setter", "FlaskAPI", "", $tags="new_container")
Container(BillingClientApi, "Client admin panel", "FastAPI", "", $tags="new_container")
ContainerQueue(BillingKafka, "interaction bus", "RabbitMq", "", $tags="new_container")
Container(BillingWorker, "State updater", "worker", "", $tags="new_container")
Container(BillingPayApi, "Pay and Paid calls", "API", "шлюз для внешних вызовов, два вызова: pay (клиент получает ссылку на этот вызов от юзер-админки, сам вызов выдает ему html-код с нужными параметрами для оплаты) и paid (коллбэк для получения результата оплаты с клиентской стороны)", $tags="new_container")
Container(Remainder, "Remainder", "", "забирает информацию из БД и шлет сообшение в очередь", $tags="new_container")
}

Container(PaymentService, "External pyment", "external API", $tags="external")

Admin -> AdminDjango: Загрузка контента
AdminDjango -> Postgres: ro/rw

Client -down-> SearchFastApiBackend: Поиск фильмов
SearchFastApiBackend -> SearchRedis: 1. Пробуем получить из КЭШа
SearchFastApiBackend -down-> SearchElastic: 2. Если в КЭШе нет идем в Elastic, после чего кладем в КЭШ
Etl -down-> Postgres: ro
Etl -> SearchElastic: перекладывает фильмы в поисковый движок

Client -up-> AuthFlask: получить токены для работы
AuthFlask -> AuthRedis
AuthFlask -up-> AuthPostgres
AuthFlask -up-> Ya
AuthFlask -up-> Vk

Client --> EventApi: просмотр фильма
EventApi -down-> Kafka

Kafka -> KafkaEtlClickhouse
KafkaEtlClickhouse -down-> ClickHouse: перекладывает данные
ClickHouse -> SomeAnalitics: аналитика менеджменту

Client -right-> ReviewsApi
ReviewsApi -down-> MongoDb
MongoDb -> Kafka

ReviewsLogstash -> ReviewsElastic
ReviewsElastic -> ReviewsKibana

NotificationsReciveApi -> RabbitMq
RabbitMq -> NotificationsSendApi
NotificationsSendApi -left-> Client
NotificationsSendApi -down-> Admin

Client -up-> BillingClientApi
Client -> BillingPayApi: редирект из Client admin panel 
Admin -> BillingAdminPriceSetterApi
BillingAdminPriceSetterApi -up-> AuthPostgres
BillingClientApi -> BillingKafka
BillingClientApi -up-> AuthPostgres
BillingKafka -> BillingWorker
BillingWorker -> AuthPostgres
BillingPayApi -up-> BillingKafka
BillingWorker -up-> PaymentService
Remainder -> AuthPostgres
Remainder -> BillingKafka

@enduml